#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
library(shiny)
library(dplyr)
library(plotly)
df <- read.csv('clean_data.csv')
genres1 <- do.call(rbind,strsplit(as.character(df$genres),'\\|'))[,1]
df1 <- data.frame(genres = genres1, select(df, -genres))

# Define UI
ui <- # Use a fluid Bootstrap layout
    fluidPage(    
        # Give the page a title
        titlePanel("Influence of average revenue from the previous years of a genre on no of movies made in that genre after those years"),
        # Generate a row with a sidebar
        sidebarLayout(      
            sidebarPanel(
                selectInput("year", label = h3("Year:"), 
                            choices=as.list(unique(df1$year))),
                selectInput("gap", "Gap (in years):", 
                            choices=as.list(1:5)),
                
                hr()
            ),
            # Create a spot for the scatter plot
            mainPanel(
                p("This shiny app is made for the purpose of testing our assumption that movie production studios tend to look at old patterns of movie genres and their financial success and try to make more movies of similar genre to earn high revenues. We did this by making a scatter plot 
                  between the average revenue generated by the movies of genres at a taken year and number of movies of these genres released after a gap (in years) from the previous years. For example, if you have chosen
                  the starting year to be 1985 and think that average time a movie takes to make is 2 years, you should select 1985 in the first drop down and 2 in the second drop down. Doing this will draw a scatterplot between average revenue of genres in 1985
                  and the number of movies released in these genres in 1987. If there is a strong positive correlation (correlation coefficient>0.7) then you can say that the data strengthens our
                  assumption. We can hover over the points to see what genres they represent, average revenue of that genre (in millions) in the selected year and the no of movies of that genre made in the selected year plus gap."),
                plotly::plotlyOutput("movieplot")  
            )
        )
    )

# Define server function
server <- function(input, output) {
    # Fill in the spot we created for a plot
    output$movieplot <- renderPlotly({
        t1 <- as.numeric(input$year)
        t2 <- t1 + as.numeric(input$gap)
        if(t2>2019)
        {
            x <- list(title = paste('Average revenue in',t1,'in millions'))
            y <- list(title = paste('Number of movies in',t2))
            p <- plot_ly(showlegend = FALSE) %>% layout(xaxis = x, yaxis = y, title="<br>One of the years has gone over 2019 <br> Please select a valid year.",  x = 0.5, y = 1,yref = "paper",
                                      xref = "paper",
                                      xanchor = "middle",
                                      yanchor = "top",
                                      yaxis = list(showticklabels = F),
                                      showarrow = FALSE,
                                      font = list(size = 15))  %>% config(displayModeBar = F)
            ggplotly(p)
        }
        else{
            tmp_t1 <- select(filter(df1, year == t1),genres, revenue)
            revenue_t1 <- tmp_t1 %>% dplyr::group_by(genres) %>% dplyr::summarise(revenue = mean(revenue, na.rm = T)) %>% ungroup()
            tmp_t2 <- select(filter(df1, year == t2),genres)
            n_movies_t2 <- tmp_t2 %>% dplyr::group_by(genres) %>% dplyr::summarise(n_t2 = n()) %>% ungroup()
            revenue_t1$revenue=revenue_t1$revenue/1000000
            o1 <- dplyr::left_join(revenue_t1, n_movies_t2, by = "genres")
            o1$n_t2[is.na(o1$n_t2)] <- 0
            max_x <- max(o1$revenue)
            max_y <- max(o1$n_t2)
            cor_coef <- cor(o1$revenue, o1$n_t2)
            #Just using NAs as 0s for calculating the correlation and then removing them from the plot
            output <- dplyr::filter(o1, n_t2 != 0)
            fit <- lm(n_t2 ~ revenue, data = output)
            # Render a scatter plot
            x <- list(title = paste('Average revenue in',t1,'in millions of dollars'))
            y <- list(title = paste('Number of movies in',t2))
            p <- plot_ly(output, x = ~revenue, y = ~n_t2, type = 'scatter', mode = 'markers',
                         text = ~paste('genre: ', genres, '\n average revenue:', round(revenue,digits=2), '\n number:',n_t2)) %>% 
            layout(xaxis = x, yaxis = y, title=paste('Influence of revenue of a genre in',t1,'\n on no of movies made in that genre in',t2,'\n\n'), annotations = list(text = paste('<b>correlation coefficient:<b>',round(cor_coef,2)),  x = 0.5, y = 1,yref = "paper",
                                                                                                                                                                                                                         xref = "paper",
                                                                                                                                                                                                                         xanchor = "middle",
                                                                                                                                                                                                                         yanchor = "bottom",
                                                                                                                                                                                                                         showarrow = FALSE,
                                                                                                                                                                                                                         font = list(size = 15)), margin = list(l=25, r=50, b=60, t=100, pad=0)) %>%
            config(displayModeBar = F)
            
            ggplotly(p)
        }
    })
}

# Create Shiny object
shinyApp(ui = ui, server = server)


